### ISSUE TITLE
 TypeError: ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by YipNZ** [Burtond/Electrodacus#1]
Hi,

Getting a strange error on my NanoPi 2K:

```
# python3 sbms0-SerialToInfluxDB.py
b'#%-56M#{LWLWLTLU##LSLTLM)0##+#,b#2,#####################%N( \n'
Traceback (most recent call last):
  File "sbms0-SerialToInfluxDB.py", line 65, in <module>
    print(str(dcmp(0, 27, var_sbms)) + str(var_sbms[28]) + str(dcmp(29, len(var_sbms)-29, var_sbms)))
  File "sbms0-SerialToInfluxDB.py", line 42, in dcmp
    wanted_ascii_character = ord(d[(p + s - 1) - z])
TypeError: ord() expected string of length 1, but int found
```
I can see that the SBMS is sending something (enabled debug statements)
Haven't checked wether the received data is actually valid yet.

Cheers.

**Comment by YipNZ** [comment]
This is a dump from miniterm.py:

```
--- Miniterm on /dev/ttyUSB0  115200,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
#%-6/\#|LkLlLjLk##LgLjLa(n##+#=/#Bc#####################%N(
#%-60%#|LjLkLiLj##LhLiLa(l##+#=9#BZ#####################%N(
#%-60*#|LjLlLjLj##LgLjLc(i##+#<|#BF#####################%N(
#%-60/#|M?KiM>Lk##LfLjLb(i##+#<o#B=#####################%N(
#%-604#|LkLkLiLj##LgLjLb(l##+#<v#BC#####################%N(
#%-609#|LlLlLiLk##LfLjLb(n##+#<}#BI#####################%N(
#%-60>#|LjLlLjLk##LgLiLb(i##+#<v#BK#####################%N(
#%-60C#|LkLkLjLk##LgLjLb(n##+#=0#BN#####################%N(
#%-60H#|LjLmLiLk##LhLjLb(l##+#=D#Bd#####################%N(

--- exit ---
```

Am I getting the right information? It almost looks truncated...

**Comment by Burtond** [comment]
Hmm, that strong looks good at first glance.  I seem to remember having a similar error running in python 3.  Stepping back to python 2 resolved my issue with the string parsing.

**Comment by YipNZ** [comment]
Ok, I'll give it a try with Python2 once I get the proper libs installed. Cheers :)

**Comment by YipNZ** [comment]
Ok, after installing pyserial and influxdb libs using pip it is now working! Thank you!

```
pip2 install pyserial
pip2 install influxdb
```
